service: stockmania

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  stage: dev
  timeout: 20
  environment:
    SESSION_NAME: ${self:service}-${opt:stage, self:provider.stage}

functions:
  login-check:
    timeout: 10
    memorySize: 128
    handler: src/login-check.handler
    events:
    - http:
        path: login-check
        method: post
        cors: true
